configuration:
  api:
    textApiUrl: https://loripsum.net/api/{0}/{1}
  kafka:
    topic: words.processed

spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
